### ISSUE TITLE
Failing to update plugin 

### ISSUE THREAD

**Issue by adalberto02** [getgauge-contrib/json-report#22]
When I select to update ( bundle exec gauge update --all) gauge plugin, I get error. 
Failed to update plugin 'json-report'.
Reason: Failed to download the plugin. Error downloading file: https://github.com/getgauge-contrib/json-report/releases/download/v0.3.5/json-report-0.3.6-darwin.x86_64.zip.

**Comment by sriv** [comment]
thanks for reporting @adalberto02 - the download links were incorrect, I've corrected them, and should be available in sometime (post cache refresh_

**Comment by adalberto02** [comment]
Thank you @sriv.

**Comment by adalberto02** [comment]
Hi @sriv, How long does the changes usually take, Im still seeing the error.

**Comment by sriv** [comment]
hi @adalberto02 - the cache refresh can take upto 12 hrs sometimes. Please check now, I am able to install v0.3.6.

**Comment by adalberto02** [comment]
Ok. Cool, yes it's fixed now. Thank you @sriv
